### ISSUE TITLE
Actualize User Stories after the interview

### ISSUE THREAD

**Issue by SnejUgal** [InnoSWP/b21-02-anonymous-feedback#19]
- [x] Describe new user stories
- [x] Merge some user stories as the client has suggested
- [x] Synchronize priorities from Notion
- [x] Make a project with the user stories

Perhaps can be done after submitting the assignment:

- [x] Describe ACs for existing user stories
