### ISSUE TITLE
Research if students trust anonymity to Telegram bots

### ISSUE THREAD

**Issue by SnejUgal** [InnoSWP/b21-02-anonymous-feedback#20]
The client asks us to make a research if students can trust their anonymity to a Telegram bot. His concern is that a Telegram bot can record the ID of its users, so students cannot be sure that the instructor will not see who wrote a particular feedback message. Therefore, the research should convince the client that students will trust a Telegram bot to deliver feedback to the instructor anonymously.

- [x] 1. Come up with a Google form/Telegram poll
- [x] 2. Conduct the research
- [x] 3. Analyze the results
