### ISSUE TITLE
Assignment 2 tracking issue

### ISSUE THREAD

**Issue by SnejUgal** [InnoSWP/b21-02-anonymous-feedback#25]
This issue tracks the progress of our Assignment 2 report.

# Functionality of the product

- [x] **Make a use-case diagram**
    We already have one, but we need to amend it:
    * #21

- [x] **Describe the features and functionality in the format of User Stories**
    Some User Stories are yet to be written, and already created ones need improvements:
    * #19
    * #22

- [x] **Create a project for your team in InnoSWP GitHub organization**
    Perhaps they meant to create this repository, as the “GitHub Projects” thing seems to be the next point

- [x] **Create your product backlog with 15..=20 items**
   We need to create a project with the prepared User Stories:
    * #19

- [x] **Make the product backlog _DEEP_**
   Is it completed? I don't know, so leaving this as unchecked

# Prototype

- [x] **We decided to go with a IU prototype in Figam, and it's already done**

# Review with the customer

- [x] **Show the prototype to the customer**

- [x] **Discuss the backlog with the customer**

- [x] **Choose to what implement in MVP v1 and future phases**
   I guess we've done that when priotized the backlog

- [x] **Update the design and the backlog based on customer feedback**
    * #19
    * #21
    * #22

# Submission

- [x] **Use case diagram**

- [x] **Link to our _DEEP_ backlog**
    Requires making a project first:
    * #19

- [x] **IU design**

- [x] **Link to our clickable prototype in Figam**

- [x] Summary of key and learning points
