### ISSUE TITLE
Iteration 0 presentation

### ISSUE THREAD

**Issue by SnejUgal** [InnoSWP/b21-02-anonymous-feedback#30]
We have to prepare a presentation with:

- [x] Team members and roles;
- [x] Introduction to the context and the problem of our product;
- [x] Use case diagram and phases;
- [x] **_DEEP_** product backlog and user stories;
- [x] Prototype;
- [x] Reflection: what went well, what didn't and how we'll fix it.

The presentation should take 5 minutes; it should be submitted as a PDF file.
