### ISSUE TITLE
Backlog routine for week 3

### ISSUE THREAD

**Issue by fedor-ivn** [InnoSWP/b21-02-anonymous-feedback#36]
# To-do

- [x]  Further groom the backlog to make it ready for the sprint meeting
- [x]  Enter your product backlog in Github Projects, arrange a board with separate lists for Product backlog, Sprint backlog, and Done.
- [x]  Create a sprint backlog in Github Projects, convert the items into issues and create a milestone corresponding to your sprint backlog.
- [x] Split the user stories for the sprint backlog into tasks and let the teammates choose the tasks. There shouldn't be any unassigned tasks left in the sprint backlog.

# Important remark

- Evaluation criteria says: correspondence between our submission & the Github Projects will be considered.
