### ISSUE TITLE
Report for week 3

### ISSUE THREAD

**Issue by fedor-ivn** [InnoSWP/b21-02-anonymous-feedback#38]
# Submit a PDF containing the following

- [x]  Link to the git repository and project at InnoSWP.
- [x]  Improved product backlog.
- [x]  Git process description.
- [x]  The sprint goal and backlog.
- [x]  The summary of what was the outcome of the sprint.
- [x]  The link to the milestone with complete issues and the corresponding pull requests.
- [x]  Report on the retrospective.

**❗️❗️❗️Double check the requirements in the assignment document.❗️❗️❗️**
