### ISSUE TITLE
Assignment 3 tracking issue

### ISSUE THREAD

**Issue by fedor-ivn** [InnoSWP/b21-02-anonymous-feedback#39]
This issue tracks the progress of our Assignment 3 report.

# Technical part

- [x] #36 
- [x] #27 
- [x] #28 
- [x] #29

# Organizational part

- [x]  Conduct a sprint review and finalize the milestone.
- [x]  Conduct a sprint retrospective.
- [x]  Plan the meeting
- [x]  Meet your customer during the week to synchronize the progress.

# Report
- [x] #37
- [x] #38 

# Evaluation Criteria

Your Sprint delivery will be evaluated based on:

- How well-structured and DEEP your backlog is.
- The sprint execution: goal, sprint backlog, review, & retrospective.
- Your Git workflow process.
- Correspondence between your submission & the Github Projects.
