### ISSUE TITLE
Report for Assignment 4

### ISSUE THREAD

**Issue by fedor-ivn** [InnoSWP/b21-02-anonymous-feedback#53]
# Submit a PDF containing the following:
- [x] Link to the git repository and project at InnoSWP.
- [x] The sprint goal, backlog.
- [x] The summary of what was the outcome of the sprint, and the link
to the milestone with complete issues and the corresponding pull
requests.
- [x] Documented quality attributes, architectural views, and
commentary.
- [x] Git workflow review.
- [x] Retrospective on the
process and customer collaboration.

❗️❗️❗️Double check the requirements in the assignment document.❗️❗️❗️
