### ISSUE TITLE
Documented quality attributes, architectural views, and commentary

### ISSUE THREAD

**Issue by fedor-ivn** [InnoSWP/b21-02-anonymous-feedback#55]
- [x] Выяснить, что именно нужно в этом пункте репорта
- [x] Взять материалы с лабы у @SnejUgal и скооперироваться, если будет нужно
- [x] Доделать материалы в соответствии с требованиями ассаймента

❗️❗️❗️При оценивании ассаймента будут уделять этому большое значение❗️❗️❗️
