### ISSUE TITLE
Assignment 4 tracking issue

### ISSUE THREAD

**Issue by fedor-ivn** [InnoSWP/b21-02-anonymous-feedback#56]
# Meeting with the customer

- [x] Arrange the meeting with the customer
- [x] Prepare the plan of the meeting
- [x] Arrange the meeting with the team before meeting with the customer

# Report
- [x] #54
- [x] #55
- [x] #53 

# Technical part
## `Must` do (by my perception)
- [x] #51 
- [x] #47 
- [x] #7 
- [x] #9 
## `Must` do, but only then (by my perception)
- [x] #48 
- [x] #50

**Comment by fedor-ivn** [comment]
#49 and #57 are moved to the next sprint
