### ISSUE TITLE
Generate short PINs for joining sessions

### ISSUE THREAD

**Issue by SnejUgal** [InnoSWP/b21-02-anonymous-feedback#57]
PINs for jojning sessions should consist of a few Latin letters and digits, e.g. `A34DF`. Perhaps these could be completely random.

# Todo

- [ ] Update GraphQL schema
- [ ] Generate random PINs on backend
- [ ] Implement "Copy join link" (#9)
- [ ] Use PINs for joining sessions in the bot
