### ISSUE TITLE
Assignment 5: Devops

### ISSUE THREAD

**Issue by SnejUgal** [InnoSWP/b21-02-anonymous-feedback#80]
- [x] **Select testing frameworks, linters, etc. and justify why**
    Perhaps any tools that will be common for the whole project?

- [x] **Set up GitHub Actions:**

    * [x] Linting
    * [x] Building testable snapshot (wtf)
    * [x] Testing
    * [x] Reports on linting and coverage 
    * [x] Any extra steps 
    
- [x] **Set up SonarCloud analysis**

Extra points will be awarded for additional, justified tools  and for 100% test coverage

**Comment by fedor-ivn** [comment]
Apart from github superlinter, I don't see any other general-purpose tools that we should utilize.

**Comment by fedor-ivn** [comment]
@SnejUgal since you've added github linter, could you justify it?

**Comment by fedor-ivn** [comment]
I propose use [codecov](https://about.codecov.io) for coverage.
