### ISSUE TITLE
Assignment 5: Report

### ISSUE THREAD

**Issue by SnejUgal** [InnoSWP/b21-02-anonymous-feedback#82]
# Report

- [x] Link to our GitHub Actions pipeline 🤡
- [x] Justified list of tools we use
- [x] Acceptance criteria for selected User Stories
- [x] Link to the sprint milestone with implemented tests and functionality
- [x] Screenshots of testing reports 🤡
- [x] Retrospective on the process 🤡 and customer collaboration
