### ISSUE TITLE
MVP Presentation 2

### ISSUE THREAD

**Issue by fedor-ivn** [InnoSWP/b21-02-anonymous-feedback#90]
# Introduction

- [x] Context
- [x] Solution

# Testing

- [x] A list of tools we use with justifications
- [x] Acceptance criteria for User Stories we selected
- [x] Screenshots of testing reports: linter reports, coverage reports, SonarCloud report

# Demo

- Should be just right, not too short or too long
- Use appropriate data during the demo
- [x] Make sure it's well prepared

# Teamwork

- [x] Sprint execution: goal, review, retrospective
- [x] Team meetings
- [x] Work distribution and planning

# Customer management

- [x] How a typical meeting is conducted
- [x] Customer feedback and satisfaction

# Lessons learned

- [x] What we learned when dealing with the client
- [x] What we learned from agile and incremental and iterative development

# Submission

- [x] Submit the slides in Moodle
