### ISSUE TITLE
Assignment 6: Sprint

### ISSUE THREAD

**Issue by SnejUgal** [InnoSWP/b21-02-anonymous-feedback#94]
- [ ] Groom the backlog
- [ ] Update our project board
- [ ] Plan the sprint:
    - [ ] Decide on the sprint goal
    - [x] Pick tasks
    - [x] Create a [milestone](https://github.com/InnoSWP/b21-02-anonymous-feedback/milestone/12)
- [ ] Execute the sprint
- [ ] Hold a sprint review
- [ ] Demonstrate progress to the customer
- [ ] Conduct a sprint retrospective

**Comment by fedor-ivn** [comment]
Sprint goal: `Complete the cycle of using guest sessions`
