### ISSUE TITLE
Assignment 6: Readme

### ISSUE THREAD

**Issue by SnejUgal** [InnoSWP/b21-02-anonymous-feedback#95]
- [x] Headline
- [x] Project description
- [x] Demo (screenshots or video)
- [x] How to use
- [x] Feature list
- [x] Project installation: we have a section “Run locally”
- [x] Frameworks or technologies used: we have a section “Stack”
- [x] Badges, at least one
- [x] Make sure that the information is well written, meaningful and descriptive

**Comment by fedor-ivn** [comment]
> Demo (screenshots or video)

IMHO, we need to update screenshots in this sprint.
