### ISSUE TITLE
Assignment 6: report

### ISSUE THREAD

**Issue by SnejUgal** [InnoSWP/b21-02-anonymous-feedback#97]
- [ ] Link to our GitHub repository with Readme
- [ ] Link to our deployed project: https://anonymous-feedback.snejugal.ru
- [ ] Link to our GitHub project board (?)
- [ ] A summary of:
    - [ ] sprint goal
    - [ ] sprint retrospective
    - [ ] sprint review
    - [ ] customer feedback
- [ ] Brief explanation of the MIT license: #96

**Comment by Hutrut** [comment]
240747
